version: '3.9'

services:

  db:
    image: postgres:17-alpine
    container_name: pim-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pim-postgres-password
      POSTGRES_DB: pim_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: